server:
    port: 8080
    servlet:
        context-path: /springbooks

spring:
    application:
        name: springbooks
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:test
        username: sa
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
          hibernate:
              format_sql: true
    h2:
        console:
            enabled: true
            path: /h2